title: Eren W. SENGUL #name
logo: "/images/profile.jpg?raw=true" #photo1
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Canadian/Cypriot/Turkish Multiple National currently living in Toronto, Ontario, Canada. I am currently looking for full-time employment or internship opportunities and I'm open to travelling and/or moving.
  <br><br>
  Click on images for contact info, and my social profiles.
  <br>
  <a href="mailto: erenwsengul@gmail.com"><img src="images/gmail_icon-icons.com_62758.png" style="width:100px; height 100px;"></a>
  <a href="https://www.linkedin.com/in/erensengul1/"><img src="images/LinkedinLogo.png" style="width:90px; height:90px;"></a>
  <a href="https://open.spotify.com/user/12184076078?si=46e106033baa4813"> <img src="images/spotify-icon.png" style ="width:105px; height:110px;"></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
