title: **Eren W. SENGUL** #name
logo: "/images/profile.jpg?raw=true?style=avatar" #photo1

description: I'm a Canadian/Cypriot/Turkish Multiple National currently living in Toronto, Ontario, Canada. I am currently looking for full-time employment or internship opportunities and I'm open to travelling and/or moving. Please feel free to contact me for references, CL or CV.
  
 
  <br>
  <br>
  
  **Click on images for contact and social info**
  
  <br>
 <a href="mailto:erenwsengul@gmail.com"><img src="images/gmail_icon-icons.com_62758.png" style="width:50px; height 50px;"></a>
  <a href="https://www.linkedin.com/in/erensengul1/"><img src="images/LinkedinLogo.png" style="width:50px; height:50px;"></a>
  <a href="https://open.spotify.com/user/12184076078?si=46e106033baa4813"> <img src="images/spotify-icon.png" style ="width:50px; height:50px;"></a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
